<a href="https://colab.research.google.com/github/shreyal18ss/pyCodes/blob/master/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [3]:
cancer_set=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data',header = None)
print(cancer_set.shape)


(569, 32)


In [4]:
print(cancer_set.head)


<bound method NDFrame.head of            0  1      2      3   ...      28      29      30       31
0      842302  M  17.99  10.38  ...  0.7119  0.2654  0.4601  0.11890
1      842517  M  20.57  17.77  ...  0.2416  0.1860  0.2750  0.08902
2    84300903  M  19.69  21.25  ...  0.4504  0.2430  0.3613  0.08758
3    84348301  M  11.42  20.38  ...  0.6869  0.2575  0.6638  0.17300
4    84358402  M  20.29  14.34  ...  0.4000  0.1625  0.2364  0.07678
..        ... ..    ...    ...  ...     ...     ...     ...      ...
564    926424  M  21.56  22.39  ...  0.4107  0.2216  0.2060  0.07115
565    926682  M  20.13  28.25  ...  0.3215  0.1628  0.2572  0.06637
566    926954  M  16.60  28.08  ...  0.3403  0.1418  0.2218  0.07820
567    927241  M  20.60  29.33  ...  0.9387  0.2650  0.4087  0.12400
568     92751  B   7.76  24.54  ...  0.0000  0.0000  0.2871  0.07039

[569 rows x 32 columns]>


In [5]:
cancer_features = cancer_set.iloc[:,2:]

print(cancer_features.shape)
print(type(cancer_features))

(569, 30)
<class 'pandas.core.frame.DataFrame'>


In [6]:
cancer_features = cancer_features.values
print(type(cancer_features))
print(cancer_features.shape)

<class 'numpy.ndarray'>
(569, 30)


In [0]:
cancer_features_names = ['mean radius', 
'mean texture', 'mean perimeter', 
'mean area', 'mean smoothness', 
'mean compactness', 'mean concavity',
'mean concave points', 'mean symmetry',
'mean fractal dimension','radius error',
'texture error','perimeter error',
'area error', 'smoothness error',
'compactness error','concavity error',
'concave points error','symmetry error',
'fractal dimension error','worst radius',
'worst texture', 'worst perimeter', 
'worst area','worst smoothness', 
'worst compactness', 'worst concavity',
'worst concave points','worst symmetry',
'worst fractal dimension']

In [8]:
cancer_target = cancer_set.iloc[:, 1]
cancer_target

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: 1, Length: 569, dtype: object

In [9]:
cancer_target = cancer_target.replace(['M', 'B'], [0, 1])
# Converting to numpy array
cancer_target = cancer_target.values
cancer_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
import sklearn.datasets as datasets

cancer = datasets.load_breast_cancer()
print(cancer.data)
print(type(cancer))
print(cancer.data.shape)
print(cancer.target.shape)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
<class 'sklearn.utils.Bunch'>
(569, 30)
(569,)


In [0]:
import sklearn.preprocessing as preprocessing

In [0]:
standardizer = preprocessing.StandardScaler()

In [0]:
standardizer = standardizer.fit(cancer.data)

In [0]:
breast_cancer_standardized = standardizer.transform(cancer.data)

In [19]:
breast_cancer_standardized

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [20]:
print('Mean of each feature after Standardization :\n\n')
print(breast_cancer_standardized.mean(axis=0))

Mean of each feature after Standardization :


[-3.16286735e-15 -6.53060890e-15 -7.07889127e-16 -8.79983452e-16
  6.13217737e-15 -1.12036918e-15 -4.42138027e-16  9.73249991e-16
 -1.97167024e-15 -1.45363120e-15 -9.07641468e-16 -8.85349205e-16
  1.77367396e-15 -8.29155139e-16 -7.54180940e-16 -3.92187747e-16
  7.91789988e-16 -2.73946068e-16 -3.10823423e-16 -3.36676596e-16
 -2.33322442e-15  1.76367415e-15 -1.19802625e-15  5.04966114e-16
 -5.21317026e-15 -2.17478837e-15  6.85645643e-16 -1.41265636e-16
 -2.28956670e-15  2.57517109e-15]


In [21]:
print('\nStd. of each feature after Standardization :\n\n')
print(breast_cancer_standardized.std(axis=0))


Std. of each feature after Standardization :


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [22]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0, 10)).fit(cancer.data)
breast_cancer_minmaxscaled10 = min_max_scaler.transform(cancer.data)
breast_cancer_minmaxscaled10.max()

10.000000000000002

In [23]:
max_abs_scaler = preprocessing.MaxAbsScaler().fit(cancer.data)

breast_cancer_maxabsscaled = max_abs_scaler.transform(cancer.data)
breast_cancer_maxabsscaled.min()

0.0

In [26]:
iris=datasets.load_iris()
normalizer=preprocessing.Normalizer().fit(iris.data)
iris_normalized=normalizer.transform(iris.data)
print(iris_normalized.mean(axis=0))

[0.75140029 0.40517418 0.45478362 0.14107142]


In [27]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [39]:
iris.target=iris.target.reshape(-1,1)
# print(iris.target)
onehotencoder=preprocessing.OneHotEncoder().fit(iris.target)
# iris_target_onehot=onehotencoder.transform(iris.target)
print(onehotencoder.transform([[0]]).toarray())
print(onehotencoder.transform([[1]]).toarray())
print(onehotencoder.transform([[2]]).toarray())

# print(iris_target_onehot.toarray([50]))
# print(iris_target_onehot.toarray([100]))
# print(iris_target_onehot.toarray([[0,50,100]]))

[[1. 0. 0.]]
[[0. 1. 0.]]
[[0. 0. 1.]]


In [51]:
import numpy as np
from sklearn.impute import SimpleImputer
iris.data[:50,:]=np.nan
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
iris_imputed=imp.fit(iris.data)
iris_imputed=imp.transform(iris.data)
print(iris_imputed.mean(axis=0))

[6.262 2.872 4.906 1.676]
